import streamlit as st
import pandas as pd

# --- TAX CALCULATION ENGINE (AUSTRALIA 2025-26) ---
def get_tax_benefit(salary, property_loss):
    """Calculates the tax refund generated by a property loss."""
    def calculate_tax(income):
        # 2025-26 Resident Tax Brackets (Simplified)
        if income <= 18200: return 0
        elif income <= 45000: return (income - 18200) * 0.16
        elif income <= 135000: return 4288 + (income - 45000) * 0.30
        elif income <= 190000: return 31288 + (income - 135000) * 0.37
        else: return 51638 + (income - 190000) * 0.45

    tax_on_salary = calculate_tax(salary)
    tax_with_property = calculate_tax(max(0, salary - property_loss))
    return tax_on_salary - tax_with_property

# --- STREAMLIT TABS ---
# (Continuing from previous tabs...)
tabs = st.tabs(["Income/Exp", "Loan Details", "Depreciation", "Tax & Gearing"])

with tabs[2]: # DEPRECIATION
    st.subheader("Non-Cash Deductions")
    st.info("These don't cost you cash but lower your tax bill.")
    col1, col2 = st.columns(2)
    div_43 = col1.number_input("Capital Works (Building - Div 43) ($)", value=6000)
    div_40 = col2.number_input("Plant & Equipment (Fixtures - Div 40) ($)", value=2500)
    total_depreciation = div_43 + div_40

with tabs[3]: # TAX & GEARING
    st.subheader("Personal Tax Impact")
    salary = st.number_input("Your Annual Salary (Before Tax) ($)", value=120000)
    
    # Logic: Rent - (Interest + Expenses + Depreciation)
    # We pull values from your previous tabs (assuming variables are defined)
    # net_rental_cash_flow = annual_gross - (annual_interest + total_ops)
    # total_tax_deduction = (annual_interest + total_ops + total_depreciation)
    
    property_tax_loss = max(0, (total_ops + annual_repayment + total_depreciation) - annual_gross)
    tax_refund = get_tax_benefit(salary, property_tax_loss)
    
    st.metric("Estimated Annual Tax Refund", f"${tax_refund:,.2f}")
    st.write(f"This property reduces your taxable income by **${property_tax_loss:,.0f}**")